# Generated by Django 4.2.1 on 2023-05-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
