# Generated by Django 4.2.1 on 2023-05-08 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motivos', '0002_bilhete_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilhete',
            name='mensagem',
        ),
        migrations.AddField(
            model_name='bilhete',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bilhete',
            name='message',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bilhete',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
